version: "3"

services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - db
    command: "./serverd"
  db:
    container_name: library_db
    image: mysql:8.0.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: library_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
volumes:
  mysql_db: